//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCrudEntityFramework.EntityModel
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class product
    {
        public int ProdId { get; set; }
        public string ProdName { get; set; }
        public string ProdImage { get; set; }
    }
}
